models/Faces.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "faces".
 *
 * @property integer $f_id
 * @property string $fullname
 * @property string $name
 * @property string $surname
 * @property string $fathersname
 * @property string $birthdate

 */
class Faces extends \yii\db\ActiveRecord
{   

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'faces';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'surname', 'fathersname', 'fullname'], 'string', 'max' => 255],
            [['name','surname','birthdate', 'fathersname'], 'required'],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'fullname' => Yii::t('app', 'Полное имя'),
            'name' => Yii::t('app', 'Имя'),
            'surname' => Yii::t('app', 'Фамилия'),
            'fathersname' => Yii::t('app', 'Отчество'),
            'birthdate' => Yii::t('app', 'Дата рождения'),
        ];
    }
    
    
    
}

models/Kids.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "kids".
 *
 * @property integer $f_id
 * @property integer $k_id
 * @property string $fullname
 * @property string $name
 * @property string $surname
 * @property string $fathersname
 * @property string $birthdate

 */
class Kids extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kids';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fullname', 'name', 'surname', 'fathersname'], 'string', 'max' => 255],
            [['name','surname','birthdate', 'fathersname'], 'required'],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'fullname' => Yii::t('app', 'Полное имя'),
            'name' => Yii::t('app', 'Имя'),
            'surname' => Yii::t('app', 'Фамилия'),
            'fathersname' => Yii::t('app', 'Отчество'),
            'birthdate' => Yii::t('app', 'Дата рождения'),
        ];
    }

    public function getFaces() {
        return $this->hasOne(\app\models\Faces::className(), ['f_id' => 'f_id']);
    }
    
    
    
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;


class SiteController extends Controller
{   
    public $enableCsrfValidation = false;

    public function behaviors()
    {   

        return [
        ];

    }


    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {   
        $array = \app\models\Faces::find()->orderBy('f_id DESC')->all();

        $model = new \app\models\Faces();

        if($model->load(Yii::$app->request->post())){
            $model->name = $_POST['Faces']['name'];
            $model->surname = $_POST['Faces']['surname'];
            $model->fathersname = $_POST['Faces']['fathersname'];
            $model->birthdate = $_POST['Faces']['birthdate'];
            $model->fullname = $model->surname." ".$model->name." ".$model->fathersname;
            $model->save();
            return $this->refresh();
        }
        return $this->render('faces', ['array'=>$array, 'model'=>$model]);
            
    }

    public function actionKids()
    {   
        $array = \app\models\Kids::find()->joinWith('faces')->orderBy('k_id DESC')->all();

        $model = new \app\models\Kids();

        if($model->load(Yii::$app->request->post())){
            $model->name = $_POST['Kids']['name'];
            $model->surname = $_POST['Kids']['surname'];
            $model->fathersname = $_POST['Kids']['fathersname'];
            $model->birthdate = $_POST['Kids']['birthdate'];
            $model->f_id = $_POST['Kids']['f_id'];
            $model->fullname = $model->surname." ".$model->name." ".$model->fathersname;
            $model->save();
            return $this->refresh();
        }
        return $this->render('kids', ['array'=>$array, 'model'=>$model]);
            
    }









}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Kulan oil',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Faces', 'url' => ['/site/index']],
            ['label' => 'Kids', 'url' => ['/site/kids']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>

<script src="https://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>

<script type="text/javascript">
    
$('#faces-birthdate').mask("9999-99-99");
$('#kids-birthdate').mask("9999-99-99");



</script>
</body>
</html>
<?php $this->endPage() ?>

views/site/faces.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datetime\DateTimePicker;


$this->title = Yii::t('user', 'Faces');
?>

<div class="row">
          <div class="col-lg-12">
            <div class="page-header">
              <h1 id="typography"><?= Html::encode($this->title) ?></h1>
            </div>
          </div>
        </div>
<div class="row">

    <div class="col-md-12">

                <?php $form = ActiveForm::begin([
                    'id'          => 'faces-form',
                    'options'     => ['class' => 'form-horizontal'],
                    'fieldConfig' => [
                        'template'     => "{label}\n<div class=\"col-lg-8\">{input}</div>\n<div class=\"col-sm-offset-4 col-lg-8\">{error}\n{hint}</div>",
                        'labelOptions' => ['class' => 'col-lg-4 control-label'],
                    ],
                ]); ?>

                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'surname') ?>
                <?= $form->field($model, 'fathersname') ?>
                <?= $form->field($model, 'birthdate')->textInput(['placeholder' => 'гггг-мм-дд']) ?>


                <div class="form-group">
                    <div class="col-lg-offset-4 col-lg-8">
                        <?= Html::submitButton(Yii::t('user', 'Добавить'), ['class' => 'btn btn-block btn-success']) ?><br>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>
 
    </div>


    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>ФИО</th>
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th>Отчество</th>
                        <th>Дата рождения</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($array as $item): ?>
                    <tr>
                        <td><?php echo $item->fullname ?></td>
                        <td><?php echo $item->name ?></td>
                        <td><?php echo $item->surname ?></td>
                        <td><?php echo $item->fathersname ?></td>
                        <td><?php echo $item->birthdate ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

views/site/kids.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datetime\DateTimePicker;
use yii\helpers\ArrayHelper;

$this->title = Yii::t('user', 'Kids');
?>

<div class="row">
          <div class="col-lg-12">
            <div class="page-header">
              <h1 id="typography"><?= Html::encode($this->title) ?></h1>
            </div>
          </div>
        </div>
<div class="row">

    <div class="col-md-12">

                <?php $form = ActiveForm::begin([
                    'id'          => 'faces-form',
                    'options'     => ['class' => 'form-horizontal'],
                    'fieldConfig' => [
                        'template'     => "{label}\n<div class=\"col-lg-8\">{input}</div>\n<div class=\"col-sm-offset-4 col-lg-8\">{error}\n{hint}</div>",
                        'labelOptions' => ['class' => 'col-lg-4 control-label'],
                    ],
                ]); ?>

                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'surname') ?>
                <?= $form->field($model, 'fathersname') ?>
                <?= $form->field($model, 'birthdate')->textInput(['placeholder' => 'гггг-мм-дд']) ?>

                <?= $form->field($model, 'f_id')->dropDownList(ArrayHelper::map(\app\models\Faces::find()->all(), 'f_id', 'name')) ?>


                <div class="form-group">
                    <div class="col-lg-offset-4 col-lg-8">
                        <?= Html::submitButton(Yii::t('user', 'Добавить'), ['class' => 'btn btn-block btn-success']) ?><br>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>
 
    </div>


    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>ФИО</th>
                        <th>Faces</th>
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th>Отчество</th>
                        <th>Дата рождения</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($array as $item): ?>
                    <tr>
                        <td><?php echo $item->fullname ?></td>
                        <td><?php echo $item->faces->name ?></td>
                        <td><?php echo $item->name ?></td>
                        <td><?php echo $item->surname ?></td>
                        <td><?php echo $item->fathersname ?></td>
                        <td><?php echo $item->birthdate ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>